[theme]
# Dark theme with black dominance and yellow as accent
primaryColor = "#FBFF47"  # Safety Yellow as accent
backgroundColor = "#101113"  # Off-black as main background
secondaryBackgroundColor = "#1E1D20"  # Dark Gray
textColor = "#FFFFFF"  # White text
font = "sans serif"  # We'll override this with custom CSS
